<MyImage01@Image>:
    source: "Background_1.png"
<MyImage02@Image>:
    source: "Background_2.png"
<MyImage03@Image>:
    source: "Background_3.png"
<MyImageTopBar@Image>:
    source: "Top_Bar.png"
    size: 480, 135
    pos: 0, 720-135

<MyImageStartBtn@Image>:
    #ボタンの中心をペアレントの中心に設定する
    #背景は透明に設定する
    source: "Start_Btn.png"
    center_x: self.parent.center_x
    center_y: self.parent.center_y

<MyImageStatsBtn@Image>:
    source: "Stats_Btn.png"
    center_x: self.parent.center_x
    center_y: self.parent.center_y

<MyImageLikesBtn@Image>:
    source: "Likes_Btn.png"
    center_x: self.parent.center_x
    center_y: self.parent.center_y


#ルートクラスを記述

MainInterface:
<MainInterface>:

    #スクリーンマネージャー下に3つのスクリーンを配置
    ScreenManager:
        id: sm
        size: root.width, root.height
        Screen:
            name: "background_1"
            MyImage01:
        Screen:
            name: "background_2"
            MyImage02:
        Screen:
            name: "background_3"
            MyImage03:

    #イメージと同じ場所にボタンを3つ配置する
    MyImageTopBar:

    Button:
        size: 112.5, 75
        pos: root.width/2 - 168.75, root.height -100
        background_color: 1,1,1,0

        #ボタンを押したら画像・スクリーンを変更する関数にパースする
        on_press: root.Start_press(Start_img, sm)
        on_release: root.Start_release(Start_img)

        MyImageStartBtn:
            id: Start_img

    Button:
        size: 112.5, 75
        pos: root.width/2 - 56.25, root.height -100
        background_color: 1,1,1,0
        on_press: root.Stats_press(Stats_img, sm)
        on_release: root.Stats_release(Stats_img)

        MyImageStatsBtn:
            id: Stats_img

    Button:
        size: 112.5, 75
        pos: root.width/2 + 56.25, root.height -100
        background_color: 1,1,1,0
        on_press: root.Likes_press(Likes_img, sm)
        on_release: root.Likes_release(Likes_img)

        MyImageLikesBtn:
            id: Likes_img